#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V2.PaidTimeOffDAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HRPaidTimeOff")]
	public partial class HRPaidTimeOffDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertENTMenuItem(ENTMenuItem instance);
    partial void UpdateENTMenuItem(ENTMenuItem instance);
    partial void DeleteENTMenuItem(ENTMenuItem instance);
    #endregion
		
		public HRPaidTimeOffDataContext() : 
				base(global::V2.PaidTimeOffDAL.Properties.Settings.Default.HRPaidTimeOffConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public HRPaidTimeOffDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HRPaidTimeOffDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HRPaidTimeOffDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HRPaidTimeOffDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ENTUserAccount> ENTUserAccounts
		{
			get
			{
				return this.GetTable<ENTUserAccount>();
			}
		}
		
		public System.Data.Linq.Table<ENTMenuItem> ENTMenuItems
		{
			get
			{
				return this.GetTable<ENTMenuItem>();
			}
		}
		
		private void InsertENTUserAccount(ENTUserAccount obj)
		{
			System.Nullable<int> p1 = obj.ENTUserAccountId;
			this.ENTUserAccountInsert(ref p1, obj.WindowsAccountName, obj.FirstName, obj.LastName, obj.Email, ((System.Nullable<bool>)(obj.IsActive)), ((System.Nullable<int>)(obj.InsertENTUserAccountId)));
			obj.ENTUserAccountId = p1.GetValueOrDefault();
		}
		
		private void UpdateENTUserAccount(ENTUserAccount obj)
		{
			this.ENTUserAccountUpdate(((System.Nullable<int>)(obj.ENTUserAccountId)), obj.WindowsAccountName, obj.FirstName, obj.LastName, obj.Email, ((System.Nullable<bool>)(obj.IsActive)), ((System.Nullable<int>)(obj.UpdateENTUserAccountId)), obj.Version);
		}
		
		private void DeleteENTUserAccount(ENTUserAccount obj)
		{
			this.ENTUserAccountDelete(((System.Nullable<int>)(obj.ENTUserAccountId)));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ENTUserAccountDelete")]
		public int ENTUserAccountDelete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ENTUserAccountId", DbType="Int")] System.Nullable<int> eNTUserAccountId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), eNTUserAccountId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ENTMenuItemSelectAll")]
		public ISingleResult<ENTMenuItem> ENTMenuItemSelectAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ENTMenuItem>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ENTUserAccountSelectAll")]
		public ISingleResult<ENTUserAccount> ENTUserAccountSelectAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ENTUserAccount>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ENTUserAccountSelectById")]
		public ISingleResult<ENTUserAccount> ENTUserAccountSelectById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ENTUserAccountId", DbType="Int")] System.Nullable<int> eNTUserAccountId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), eNTUserAccountId);
			return ((ISingleResult<ENTUserAccount>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ENTUserAccountInsert")]
		public int ENTUserAccountInsert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ENTUserAccountId", DbType="Int")] ref System.Nullable<int> eNTUserAccountId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="WindowsAccountName", DbType="VarChar(50)")] string windowsAccountName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FirstName", DbType="NVarChar(50)")] string firstName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastName", DbType="NVarChar(50)")] string lastName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(100)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsActive", DbType="Bit")] System.Nullable<bool> isActive, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="InsertENTUserAccountId", DbType="Int")] System.Nullable<int> insertENTUserAccountId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), eNTUserAccountId, windowsAccountName, firstName, lastName, email, isActive, insertENTUserAccountId);
			eNTUserAccountId = ((System.Nullable<int>)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ENTUserAccountUpdate")]
		public int ENTUserAccountUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ENTUserAccountId", DbType="Int")] System.Nullable<int> eNTUserAccountId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="WindowsAccountName", DbType="VarChar(50)")] string windowsAccountName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FirstName", DbType="NVarChar(50)")] string firstName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LastName", DbType="NVarChar(50)")] string lastName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(100)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsActive", DbType="Bit")] System.Nullable<bool> isActive, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UpdateENTUserAccountId", DbType="Int")] System.Nullable<int> updateENTUserAccountId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Version", DbType="rowversion")] System.Data.Linq.Binary version)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), eNTUserAccountId, windowsAccountName, firstName, lastName, email, isActive, updateENTUserAccountId, version);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ENTUserAccount")]
	public partial class ENTUserAccount : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ENTUserAccountId;
		
		private string _WindowsAccountName;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _Email;
		
		private bool _IsActive;
		
		private System.DateTime _InsertDate;
		
		private int _InsertENTUserAccountId;
		
		private System.DateTime _UpdateDate;
		
		private int _UpdateENTUserAccountId;
		
		private System.Data.Linq.Binary _Version;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnENTUserAccountIdChanging(int value);
    partial void OnENTUserAccountIdChanged();
    partial void OnWindowsAccountNameChanging(string value);
    partial void OnWindowsAccountNameChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnIsActiveChanging(bool value);
    partial void OnIsActiveChanged();
    partial void OnInsertDateChanging(System.DateTime value);
    partial void OnInsertDateChanged();
    partial void OnInsertENTUserAccountIdChanging(int value);
    partial void OnInsertENTUserAccountIdChanged();
    partial void OnUpdateDateChanging(System.DateTime value);
    partial void OnUpdateDateChanged();
    partial void OnUpdateENTUserAccountIdChanging(int value);
    partial void OnUpdateENTUserAccountIdChanged();
    partial void OnVersionChanging(System.Data.Linq.Binary value);
    partial void OnVersionChanged();
    #endregion
		
		public ENTUserAccount()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENTUserAccountId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int ENTUserAccountId
		{
			get
			{
				return this._ENTUserAccountId;
			}
			set
			{
				if ((this._ENTUserAccountId != value))
				{
					this.OnENTUserAccountIdChanging(value);
					this.SendPropertyChanging();
					this._ENTUserAccountId = value;
					this.SendPropertyChanged("ENTUserAccountId");
					this.OnENTUserAccountIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WindowsAccountName", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string WindowsAccountName
		{
			get
			{
				return this._WindowsAccountName;
			}
			set
			{
				if ((this._WindowsAccountName != value))
				{
					this.OnWindowsAccountNameChanging(value);
					this.SendPropertyChanging();
					this._WindowsAccountName = value;
					this.SendPropertyChanged("WindowsAccountName");
					this.OnWindowsAccountNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertDate", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime InsertDate
		{
			get
			{
				return this._InsertDate;
			}
			set
			{
				if ((this._InsertDate != value))
				{
					this.OnInsertDateChanging(value);
					this.SendPropertyChanging();
					this._InsertDate = value;
					this.SendPropertyChanged("InsertDate");
					this.OnInsertDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertENTUserAccountId", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int InsertENTUserAccountId
		{
			get
			{
				return this._InsertENTUserAccountId;
			}
			set
			{
				if ((this._InsertENTUserAccountId != value))
				{
					this.OnInsertENTUserAccountIdChanging(value);
					this.SendPropertyChanging();
					this._InsertENTUserAccountId = value;
					this.SendPropertyChanged("InsertENTUserAccountId");
					this.OnInsertENTUserAccountIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				if ((this._UpdateDate != value))
				{
					this.OnUpdateDateChanging(value);
					this.SendPropertyChanging();
					this._UpdateDate = value;
					this.SendPropertyChanged("UpdateDate");
					this.OnUpdateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateENTUserAccountId", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int UpdateENTUserAccountId
		{
			get
			{
				return this._UpdateENTUserAccountId;
			}
			set
			{
				if ((this._UpdateENTUserAccountId != value))
				{
					this.OnUpdateENTUserAccountIdChanging(value);
					this.SendPropertyChanging();
					this._UpdateENTUserAccountId = value;
					this.SendPropertyChanged("UpdateENTUserAccountId");
					this.OnUpdateENTUserAccountIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Version", AutoSync=AutoSync.Always, DbType="rowversion", IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Version
		{
			get
			{
				return this._Version;
			}
			set
			{
				if ((this._Version != value))
				{
					this.OnVersionChanging(value);
					this.SendPropertyChanging();
					this._Version = value;
					this.SendPropertyChanged("Version");
					this.OnVersionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ENTMenuItem")]
	public partial class ENTMenuItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ENTMenuItemId;
		
		private string _MenuItemName;
		
		private string _Description;
		
		private string _Url;
		
		private System.Nullable<int> _ParentENTMenuItemId;
		
		private byte _DisplaySequence;
		
		private bool _IsAlwaysEnabled;
		
		private System.DateTime _InsertDate;
		
		private int _InsertENTUserAccountId;
		
		private System.DateTime _UpdateDate;
		
		private int _UpdateENTUserAccountId;
		
		private System.Data.Linq.Binary _Version;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnENTMenuItemIdChanging(int value);
    partial void OnENTMenuItemIdChanged();
    partial void OnMenuItemNameChanging(string value);
    partial void OnMenuItemNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnUrlChanging(string value);
    partial void OnUrlChanged();
    partial void OnParentENTMenuItemIdChanging(System.Nullable<int> value);
    partial void OnParentENTMenuItemIdChanged();
    partial void OnDisplaySequenceChanging(byte value);
    partial void OnDisplaySequenceChanged();
    partial void OnIsAlwaysEnabledChanging(bool value);
    partial void OnIsAlwaysEnabledChanged();
    partial void OnInsertDateChanging(System.DateTime value);
    partial void OnInsertDateChanged();
    partial void OnInsertENTUserAccountIdChanging(int value);
    partial void OnInsertENTUserAccountIdChanged();
    partial void OnUpdateDateChanging(System.DateTime value);
    partial void OnUpdateDateChanged();
    partial void OnUpdateENTUserAccountIdChanging(int value);
    partial void OnUpdateENTUserAccountIdChanged();
    partial void OnVersionChanging(System.Data.Linq.Binary value);
    partial void OnVersionChanged();
    #endregion
		
		public ENTMenuItem()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENTMenuItemId", DbType="Int NOT NULL", IsPrimaryKey=true, UpdateCheck=UpdateCheck.Never)]
		public int ENTMenuItemId
		{
			get
			{
				return this._ENTMenuItemId;
			}
			set
			{
				if ((this._ENTMenuItemId != value))
				{
					this.OnENTMenuItemIdChanging(value);
					this.SendPropertyChanging();
					this._ENTMenuItemId = value;
					this.SendPropertyChanged("ENTMenuItemId");
					this.OnENTMenuItemIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuItemName", DbType="VarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string MenuItemName
		{
			get
			{
				return this._MenuItemName;
			}
			set
			{
				if ((this._MenuItemName != value))
				{
					this.OnMenuItemNameChanging(value);
					this.SendPropertyChanging();
					this._MenuItemName = value;
					this.SendPropertyChanged("MenuItemName");
					this.OnMenuItemNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url", DbType="VarChar(MAX)", UpdateCheck=UpdateCheck.Never)]
		public string Url
		{
			get
			{
				return this._Url;
			}
			set
			{
				if ((this._Url != value))
				{
					this.OnUrlChanging(value);
					this.SendPropertyChanging();
					this._Url = value;
					this.SendPropertyChanged("Url");
					this.OnUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentENTMenuItemId", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> ParentENTMenuItemId
		{
			get
			{
				return this._ParentENTMenuItemId;
			}
			set
			{
				if ((this._ParentENTMenuItemId != value))
				{
					this.OnParentENTMenuItemIdChanging(value);
					this.SendPropertyChanging();
					this._ParentENTMenuItemId = value;
					this.SendPropertyChanged("ParentENTMenuItemId");
					this.OnParentENTMenuItemIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplaySequence", DbType="TinyInt NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public byte DisplaySequence
		{
			get
			{
				return this._DisplaySequence;
			}
			set
			{
				if ((this._DisplaySequence != value))
				{
					this.OnDisplaySequenceChanging(value);
					this.SendPropertyChanging();
					this._DisplaySequence = value;
					this.SendPropertyChanged("DisplaySequence");
					this.OnDisplaySequenceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAlwaysEnabled", DbType="Bit NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public bool IsAlwaysEnabled
		{
			get
			{
				return this._IsAlwaysEnabled;
			}
			set
			{
				if ((this._IsAlwaysEnabled != value))
				{
					this.OnIsAlwaysEnabledChanging(value);
					this.SendPropertyChanging();
					this._IsAlwaysEnabled = value;
					this.SendPropertyChanged("IsAlwaysEnabled");
					this.OnIsAlwaysEnabledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertDate", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime InsertDate
		{
			get
			{
				return this._InsertDate;
			}
			set
			{
				if ((this._InsertDate != value))
				{
					this.OnInsertDateChanging(value);
					this.SendPropertyChanging();
					this._InsertDate = value;
					this.SendPropertyChanged("InsertDate");
					this.OnInsertDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertENTUserAccountId", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int InsertENTUserAccountId
		{
			get
			{
				return this._InsertENTUserAccountId;
			}
			set
			{
				if ((this._InsertENTUserAccountId != value))
				{
					this.OnInsertENTUserAccountIdChanging(value);
					this.SendPropertyChanging();
					this._InsertENTUserAccountId = value;
					this.SendPropertyChanged("InsertENTUserAccountId");
					this.OnInsertENTUserAccountIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public System.DateTime UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				if ((this._UpdateDate != value))
				{
					this.OnUpdateDateChanging(value);
					this.SendPropertyChanging();
					this._UpdateDate = value;
					this.SendPropertyChanged("UpdateDate");
					this.OnUpdateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateENTUserAccountId", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int UpdateENTUserAccountId
		{
			get
			{
				return this._UpdateENTUserAccountId;
			}
			set
			{
				if ((this._UpdateENTUserAccountId != value))
				{
					this.OnUpdateENTUserAccountIdChanging(value);
					this.SendPropertyChanging();
					this._UpdateENTUserAccountId = value;
					this.SendPropertyChanged("UpdateENTUserAccountId");
					this.OnUpdateENTUserAccountIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Version", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Version
		{
			get
			{
				return this._Version;
			}
			set
			{
				if ((this._Version != value))
				{
					this.OnVersionChanging(value);
					this.SendPropertyChanging();
					this._Version = value;
					this.SendPropertyChanged("Version");
					this.OnVersionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
